#!/usr/bin/env bash

set -e

npm uninstall react react-dom react-addons-test-utils || true

if [ "$REACT" == "13" ]; then
  npm install react@0.13
elif [ "$REACT" == "14" ]; then
  npm install react@0.14 react-dom@0.14 react-addons-test-utils@0.14
else
  npm install react@$REACT react-dom@$REACT react-addons-test-utils@$REACT
fi

npm test
